import type { LucideProps } from "lucide-react";
import {
  AppWindow,
  Apple,
  ArrowUpRight,
  BadgeCheck,
  Blocks,
  Bot,
  Braces,
  CheckCircle2,
  Cloud,
  CloudCog,
  CloudUpload,
  Code2,
  CreditCard,
  Database,
  ExternalLink,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe2,
  Layers3,
  LayoutDashboard,
  LifeBuoy,
  LockKeyhole,
  MapPin,
  MapPinned,
  MessageSquare,
  MessagesSquare,
  PanelTop,
  PenTool,
  PlugZap,
  Radio,
  Rocket,
  Search,
  Send,
  ServerCog,
  Server,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  TestTube2,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  AppWindow,
  Apple,
  BadgeCheck,
  Blocks,
  Bot,
  Braces,
  CloudCog,
  CloudUpload,
  Code2,
  CreditCard,
  Database,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe2,
  Layers3,
  LayoutDashboard,
  MapPinned,
  MessageSquare,
  PanelTop,
  PenTool,
  PlugZap,
  Radio,
  Rocket,
  Search,
  Server,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  Wrench,
  app: AppWindow,
  arrow: ArrowUpRight,
  bot: Bot,
  braces: Braces,
  check: CheckCircle2,
  cloud: Cloud,
  code: Code2,
  creditCard: CreditCard,
  database: Database,
  external: ExternalLink,
  globe: Globe2,
  layers: Layers3,
  layout: LayoutDashboard,
  lifeBuoy: LifeBuoy,
  lock: LockKeyhole,
  mapPin: MapPin,
  messages: MessagesSquare,
  pen: PenTool,
  rocket: Rocket,
  search: Search,
  send: Send,
  server: ServerCog,
  smartphone: Smartphone,
  sparkles: Sparkles,
  store: Store,
  test: TestTube2,
  wifi: Wifi,
  wrench: Wrench,
};

type IconProps = LucideProps & {
  name: string;
};

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name] ?? Sparkles;
  return <IconComponent {...props} />;
}
